#!/bin/bash
# Old, doesn't always work depending on spacing around `\( \)`
# pbpaste | sed -e 's/\\\[/$$/g' -e 's/\\\]/$$/g' -e 's/\\( /$/g' -e 's/ \\)/$/g' | pbcopy

# New, works. Generated by `o1-mini-high` on 2 February 2025

pbpaste | perl -e '
use strict;
use warnings;

# Read all lines from STDIN.
my @lines = <STDIN>;
chomp(@lines);

# --- Step 1. Convert inline math delimiters ---
# Replace “\(...” (with optional spaces) with “$” and “...\)” (with optional spaces) with “$”
for (@lines) {
    s/\\\(\s*/\$/g;
    s/\s*\\\)/\$/g;
}

# --- Step 2. Convert display math delimiters ---
# If a line contains only “\[” or “\]” (with optional whitespace), convert it to literal “$$”.
for (@lines) {
    if (/^\s*\\\[\s*$/) {
        $_ = "\$\$";
    }
    if (/^\s*\\\]\s*$/) {
        $_ = "\$\$";
    }
}

# --- Step 3. Insert blank lines around display math blocks ---
# We assume display math delimiters (now “$$”) appear on lines by themselves.
# When encountering a “$$” and not already inside a display block, treat it as the opening delimiter;
# insert a blank line before it if the previous output line isn’t already blank.
# When encountering a “$$” while inside a display block, treat it as the closing delimiter;
# output it and insert a blank line after it if the next input line isn’t already blank.
my $in_display = 0;
my @out;
for (my $i = 0; $i < @lines; $i++) {
    my $line = $lines[$i];
    if ($line =~ /^\s*\$\$\s*$/) {
        if (!$in_display) {
            # This is an opening delimiter.
            if (@out && $out[-1] !~ /^\s*$/) {
                push @out, "";
            }
            push @out, "\$\$";
            $in_display = 1;
        } else {
            # This is a closing delimiter.
            push @out, "\$\$";
            $in_display = 0;
            # Insert a blank line after the closing delimiter if the next line exists and isn’t blank.
            if ($i < $#lines && $lines[$i+1] !~ /^\s*$/) {
                push @out, "";
            }
        }
    }
    else {
        push @out, $line;
    }
}

# --- Step 4. Insert a blank line before the start of a list block ---
# If a line starts with a list marker (e.g., "-", "*", "+", or a numbered item like "1.")
# and the previous output line is neither blank nor already a list item,
# insert a blank line. This ensures only a single blank line appears before the list.
my @final;
foreach my $line (@out) {
    if ($line =~ /^\s*(?:[-*+]|(?:\d+\.)\s+)/) {
        if (@final
            && $final[-1] !~ /^\s*$/    # previous line is not blank
            && $final[-1] !~ /^\s*(?:[-*+]|(?:\d+\.)\s+)/  # previous line is not already a list item
           ) {
            push @final, "";
        }
    }
    push @final, $line;
}

print join("\n", @final), "\n";
' | pbcopy
